### ISSUE TITLE
partitioned tables in config

### ISSUE THREAD

**Issue by mkabilov** [mkabilov/pg2ch#23]
in case of setting up replication for child tables of the partitioned table it will be useful to specify pattern for tables, i.e. instead of :
```yaml
    partitions.report_2017_03_01:
        main_table: report
        engine: CollapsingMergeTree
        init_sync_skip_truncate: true
    partitions.report_2017_04_01:
        main_table: report
        engine: CollapsingMergeTree
        init_sync_skip_truncate: true
    partitions.report_2017_05_01:
        main_table: report
        engine: CollapsingMergeTree
        init_sync_skip_truncate: true
    partitions.report_2017_01_01:
        main_table: report
        engine: CollapsingMergeTree
        init_sync_skip_truncate: true
``` 

write something like that:
```yaml
    partitions.report_*:
        main_table: report
        engine: CollapsingMergeTree
        init_sync_skip_truncate: true
```
TBD
